insert into factura_vigente values (null, 2019, null, 'folio1', 1, 10, '2019-01-01', null, 'rfc1');
insert into factura_vigente values (null, 2019, null, 'folio2', 1, 20, '2019-01-01', null, 'rfc2');
insert into factura_vigente values (null, 2019, null, 'folio3', 1, 30, '2019-01-01', null, 'rfc3');
-- create table public.factura_vigente (id integer generated by default as identity, ano double, fecha_inicio_depreciacion date, folio varchar(100), mes double, monto double, periodo date, porcentaje double, rfc_emisor varchar(50), primary key (id))