package org.nada.models;
// Generated Mar 9, 2020, 6:42:38 PM by Hibernate Tools 5.2.5.Final


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * DeclaracionConceptoFactura generated by hbm2java
 */
@Entity
@Table(name="declaracion_concepto_factura"
    ,schema="public"
)
public class DeclaracionConceptoFactura  implements java.io.Serializable {


     private Integer id;
     private ConceptoFactura conceptoFactura;
     private DeclaracionFactura declaracionFactura;
     private Date tiempoCreacion;

    public DeclaracionConceptoFactura() {
    }

	
    public DeclaracionConceptoFactura(Date tiempoCreacion) {
        this.tiempoCreacion = tiempoCreacion;
    }
    public DeclaracionConceptoFactura(ConceptoFactura conceptoFactura, DeclaracionFactura declaracionFactura, Date tiempoCreacion) {
       this.conceptoFactura = conceptoFactura;
       this.declaracionFactura = declaracionFactura;
       this.tiempoCreacion = tiempoCreacion;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="id", unique=true, nullable=false)
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="id_concepto_factura")
    public ConceptoFactura getConceptoFactura() {
        return this.conceptoFactura;
    }
    
    public void setConceptoFactura(ConceptoFactura conceptoFactura) {
        this.conceptoFactura = conceptoFactura;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="id_declaracion_factura")
    public DeclaracionFactura getDeclaracionFactura() {
        return this.declaracionFactura;
    }
    
    public void setDeclaracionFactura(DeclaracionFactura declaracionFactura) {
        this.declaracionFactura = declaracionFactura;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="tiempo_creacion", nullable=false, length=29)
    public Date getTiempoCreacion() {
        return this.tiempoCreacion;
    }
    
    public void setTiempoCreacion(Date tiempoCreacion) {
        this.tiempoCreacion = tiempoCreacion;
    }




}


