package org.nada.models;
// Generated Mar 9, 2020, 4:37:16 PM by Hibernate Tools 5.2.5.Final


import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.OneToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.Transient;
import org.apache.commons.lang3.builder.ToStringBuilder;

/**
 * DeclaracionFactura generated by hbm2java
 */
@Entity
@Table(name="declaracion_factura"
    ,schema="public"
)
public class DeclaracionFactura  implements java.io.Serializable {


     private Integer id;
     private Factura factura;
     private FechaInicioDepreciacionFactura fechaInicioDepreciacionFactura;
     private MontoDeducibleFactura montoDeducibleFactura;
     private MontoFactura montoFactura;
     private PorcentajeDepreciacionAnualFactura porcentajeDepreciacionAnualFactura;
     private Integer idDeclaracion;
     private Date tiempoCreacion;
     private Set<DeclaracionConceptoFactura> declaracionConceptoFacturas = new HashSet<DeclaracionConceptoFactura>(0);

    public DeclaracionFactura() {
    }

	
    public DeclaracionFactura(Factura factura, MontoFactura montoFactura, Integer idDeclaracion) {
        this.factura = factura;
        this.montoFactura = montoFactura;
        this.idDeclaracion = idDeclaracion;
    }
    public DeclaracionFactura(Factura factura, FechaInicioDepreciacionFactura fechaInicioDepreciacionFactura, MontoDeducibleFactura montoDeducibleFactura, MontoFactura montoFactura, PorcentajeDepreciacionAnualFactura porcentajeDepreciacionAnualFactura, Integer idDeclaracion, Date tiempoCreacion, Set<DeclaracionConceptoFactura> declaracionConceptoFacturas) {
       this.factura = factura;
       this.fechaInicioDepreciacionFactura = fechaInicioDepreciacionFactura;
       this.montoDeducibleFactura = montoDeducibleFactura;
       this.montoFactura = montoFactura;
       this.porcentajeDepreciacionAnualFactura = porcentajeDepreciacionAnualFactura;
       this.idDeclaracion = idDeclaracion;
       this.tiempoCreacion = tiempoCreacion;
       this.declaracionConceptoFacturas = declaracionConceptoFacturas;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="id", unique=true, nullable=false)
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="id_factura", nullable=false)
    public Factura getFactura() {
        return this.factura;
    }
    
    public void setFactura(Factura factura) {
        this.factura = factura;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="id_fecha_inicio_depreciacion")
    public FechaInicioDepreciacionFactura getFechaInicioDepreciacionFactura() {
        return this.fechaInicioDepreciacionFactura;
    }
    
    public void setFechaInicioDepreciacionFactura(FechaInicioDepreciacionFactura fechaInicioDepreciacionFactura) {
        this.fechaInicioDepreciacionFactura = fechaInicioDepreciacionFactura;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="id_monto_deducible")
    public MontoDeducibleFactura getMontoDeducibleFactura() {
        return this.montoDeducibleFactura;
    }
    
    public void setMontoDeducibleFactura(MontoDeducibleFactura montoDeducibleFactura) {
        this.montoDeducibleFactura = montoDeducibleFactura;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="id_monto", nullable=false)
    public MontoFactura getMontoFactura() {
        return this.montoFactura;
    }
    
    public void setMontoFactura(MontoFactura montoFactura) {
        this.montoFactura = montoFactura;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="id_porcentaje_depreciacion")
    public PorcentajeDepreciacionAnualFactura getPorcentajeDepreciacionAnualFactura() {
        return this.porcentajeDepreciacionAnualFactura;
    }
    
    public void setPorcentajeDepreciacionAnualFactura(PorcentajeDepreciacionAnualFactura porcentajeDepreciacionAnualFactura) {
        this.porcentajeDepreciacionAnualFactura = porcentajeDepreciacionAnualFactura;
    }

    
    @Column(name="id_declaracion", nullable=false)
    public Integer getIdDeclaracion() {
        return this.idDeclaracion;
    }
    
    public void setIdDeclaracion(Integer idDeclaracion) {
        this.idDeclaracion = idDeclaracion;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="tiempo_creacion", length=29)
    public Date getTiempoCreacion() {
        return this.tiempoCreacion;
    }
    
    public void setTiempoCreacion(Date tiempoCreacion) {
        this.tiempoCreacion = tiempoCreacion;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="declaracionFactura")
    public Set<DeclaracionConceptoFactura> getDeclaracionConceptoFacturas() {
        return this.declaracionConceptoFacturas;
    }
    
    public void setDeclaracionConceptoFacturas(Set<DeclaracionConceptoFactura> declaracionConceptoFacturas) {
        this.declaracionConceptoFacturas = declaracionConceptoFacturas;
    }



  // The following is extra code specified in the hbm.xml files

        
// Aca nomas probando controla la autodegeneracion con <<class-code >>
// TODO: https://stackoverflow.com/questions/2653268/what-are-the-shortcut-to-auto-generating-tostring-method-in-eclipse
public String toString() { return ToStringBuilder.reflectionToString(this); }

	private DeclaracionVigente declaracionVigente;

	@ManyToOne(targetEntity = DeclaracionVigente.class)
	@JoinColumn(name = "id_declaracion", updatable = false, insertable = false)
	public DeclaracionVigente getDeclaracionVigente() {
		return declaracionVigente;
	}

	public void setDeclaracionVigente(DeclaracionVigente declaracionVigente) {
		this.declaracionVigente = declaracionVigente;
	}

private FacturaVigente facturaVigente;
	private FacturaVigenteExtendida facturaVigenteExtendida;

	@OneToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_factura", updatable = false, insertable = false)
	public FacturaVigente getFacturaVigente() {
		return facturaVigente;
	}

	public void setFacturaVigente(FacturaVigente facturaVigente) {
		this.facturaVigente = facturaVigente;
	}
        
		
  // end of extra code specified in the hbm.xml files

	@Transient
	public FacturaVigenteExtendida getFacturaVigenteExtendida() {
		if (facturaVigenteExtendida == null) {
			facturaVigenteExtendida = new FacturaVigenteExtendida(getFacturaVigente());
		}
		return facturaVigenteExtendida;
	}


        
		
  // end of extra code specified in the hbm.xml files

}


