package org.nada.models;
// Generated 13 abr 2019 13:14:22 by Hibernate Tools 5.2.5.Final


import java.util.Date;
import java.util.List;
import java.util.stream.Collectors;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.Transient;

/**
 * FacturaVigente generated by hbm2java
 */
@Entity
@Table(name="factura_vigente"
    ,schema="public"
)
public class FacturaVigente  implements java.io.Serializable {


     private Integer id;
     private String rfcEmisor;
     private String folio;
     private Double monto;
     private Double porcentaje;
     private Date fecha;
     private Double ano;
     private Double mes;
     private Double montoDepreciado;

    public FacturaVigente() {
    }

    public FacturaVigente(String rfcEmisor, String folio, Double monto, Double porcentaje, Date fecha, Double ano, Double mes, Double montoDepreciado) {
       this.rfcEmisor = rfcEmisor;
       this.folio = folio;
       this.monto = monto;
       this.porcentaje = porcentaje;
       this.fecha = fecha;
       this.ano = ano;
       this.mes = mes;
       this.montoDepreciado = montoDepreciado;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="id", nullable=false)
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }

    
    @Column(name="rfc_emisor", length=50)
    public String getRfcEmisor() {
        return this.rfcEmisor;
    }
    
    public void setRfcEmisor(String rfcEmisor) {
        this.rfcEmisor = rfcEmisor;
    }

    
    @Column(name="folio", length=100)
    public String getFolio() {
        return this.folio;
    }
    
    public void setFolio(String folio) {
       
				// Aqui nomas probando controlar la degeneracion por plantillas && 
				
				
			 
        this.folio = folio;
    }

    
    @Column(name="monto", precision=17, scale=17)
    public Double getMonto() {
        return this.monto;
    }
    
    public void setMonto(Double monto) {
        this.monto = monto;
    }

    
    @Column(name="porcentaje", precision=17, scale=17)
    public Double getPorcentaje() {
        return this.porcentaje;
    }
    
    public void setPorcentaje(Double porcentaje) {
        this.porcentaje = porcentaje;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="fecha", length=13)
    public Date getFecha() {
        return this.fecha;
    }
    
    public void setFecha(Date fecha) {
        this.fecha = fecha;
    }

    
    @Column(name="ano", precision=17, scale=17)
    public Double getAno() {
        return this.ano;
    }
    
    public void setAno(Double ano) {
        this.ano = ano;
    }

    
    @Column(name="mes", precision=17, scale=17)
    public Double getMes() {
        return this.mes;
    }
    
    public void setMes(Double mes) {
        this.mes = mes;
    }

    
    @Column(name="monto_depreciado", precision=17, scale=17)
    public Double getMontoDepreciado() {
        return this.montoDepreciado;
    }
    
    public void setMontoDepreciado(Double montoDepreciado) {
        this.montoDepreciado = montoDepreciado;
    }



  // The following is extra code specified in the hbm.xml files

        
// Aca nomas probando controla la autodegeneracion con <<class-code >>
        
		
  // end of extra code specified in the hbm.xml files

}


