package org.nada.models;
// Generated 18 abr 2019 20:47:39 by Hibernate Tools 5.2.5.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import org.apache.commons.lang3.builder.ToStringBuilder;

/**
 * MontoFactura generated by hbm2java
 */
@Entity
@Table(name = "monto_factura", schema = "public")
public class MontoFactura implements java.io.Serializable {

	private Integer id;
	private Factura factura;
	private Double monto;
	private Date tiempoCreacion;

	public MontoFactura() {
	}

	public MontoFactura(Double monto, Date tiempoCreacion) {
		this.monto = monto;
		this.tiempoCreacion = tiempoCreacion;
	}

	public MontoFactura(Factura factura, Double monto, Date tiempoCreacion) {
		this.factura = factura;
		this.monto = monto;
		this.tiempoCreacion = tiempoCreacion;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_factura")
	public Factura getFactura() {
		return this.factura;
	}

	public void setFactura(Factura factura) {
		this.factura = factura;
	}

	@Column(name = "monto", nullable = false, precision = 17, scale = 17)
	public Double getMonto() {
		return this.monto;
	}

	public void setMonto(Double monto) {
		this.monto = monto;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "tiempo_creacion", nullable = false, length = 29)
	public Date getTiempoCreacion() {
		return this.tiempoCreacion;
	}

	public void setTiempoCreacion(Date tiempoCreacion) {
		this.tiempoCreacion = tiempoCreacion;
	}

	public String toString() {
		return ToStringBuilder.reflectionToString(this);
	}

}
