package org.nada.models;
// Generated 13 abr 2019 13:14:22 by Hibernate Tools 5.2.5.Final


import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * MontoFacturaVigente generated by hbm2java
 */
@Entity
@Table(name="monto_factura_vigente"
    ,schema="public"
)
public class MontoFacturaVigente  implements java.io.Serializable {


     private MontoFacturaVigenteId id;

    public MontoFacturaVigente() {
    }

    public MontoFacturaVigente(MontoFacturaVigenteId id) {
       this.id = id;
    }
   
     @EmbeddedId

    
    @AttributeOverrides( {
        @AttributeOverride(name="id", column=@Column(name="id") ), 
        @AttributeOverride(name="monto", column=@Column(name="monto", precision=17, scale=17) ), 
        @AttributeOverride(name="tiempoCreacion", column=@Column(name="tiempo_creacion", length=29) ), 
        @AttributeOverride(name="idFactura", column=@Column(name="id_factura") ), 
        @AttributeOverride(name="ultimoCreado", column=@Column(name="ultimo_creado", length=29) ) } )
    public MontoFacturaVigenteId getId() {
        return this.id;
    }
    
    public void setId(MontoFacturaVigenteId id) {
        this.id = id;
    }




}


