package org.nada.models;
// Generated 17 abr 2019 6:03:36 by Hibernate Tools 5.2.5.Final


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * PorcentajeDepreciacionAnualFactura generated by hbm2java
 */
@Entity
@Table(name="porcentaje_depreciacion_anual_factura"
    ,schema="public"
)
public class PorcentajeDepreciacionAnualFactura  implements java.io.Serializable {


     private Integer id;
     private Factura factura;
     private double porcentaje;
     private Date tiempoCreacion;

    public PorcentajeDepreciacionAnualFactura() {
    }

	
    public PorcentajeDepreciacionAnualFactura(double porcentaje, Date tiempoCreacion) {
        this.porcentaje = porcentaje;
        this.tiempoCreacion = tiempoCreacion;
    }
    public PorcentajeDepreciacionAnualFactura(Factura factura, double porcentaje, Date tiempoCreacion) {
       this.factura = factura;
       this.porcentaje = porcentaje;
       this.tiempoCreacion = tiempoCreacion;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="id", nullable=false)
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="id_factura")
    public Factura getFactura() {
        return this.factura;
    }
    
    public void setFactura(Factura factura) {
        this.factura = factura;
    }

    
    @Column(name="porcentaje", nullable=false, precision=17, scale=17)
    public double getPorcentaje() {
        return this.porcentaje;
    }
    
    public void setPorcentaje(double porcentaje) {
        this.porcentaje = porcentaje;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="tiempo_creacion", nullable=false, length=29)
    public Date getTiempoCreacion() {
        return this.tiempoCreacion;
    }
    
    public void setTiempoCreacion(Date tiempoCreacion) {
        this.tiempoCreacion = tiempoCreacion;
    }




}


