package org.nada.models;
// Generated 26 dic 2019 20:41:46 by Hibernate Tools 5.2.5.Final


import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * PorcentajeDepreciacionAnualFactura generated by hbm2java
 */
@Entity
@Table(name="porcentaje_depreciacion_anual_factura"
    ,schema="public"
)
public class PorcentajeDepreciacionAnualFactura  implements java.io.Serializable {


     private Integer id;
     private Factura factura;
     private Double porcentaje;
     private Date tiempoCreacion;
     private Set<DeclaracionFactura> declaracionFacturas = new HashSet<DeclaracionFactura>(0);

    public PorcentajeDepreciacionAnualFactura() {
    }

	
    public PorcentajeDepreciacionAnualFactura(Double porcentaje, Date tiempoCreacion) {
        this.porcentaje = porcentaje;
        this.tiempoCreacion = tiempoCreacion;
    }
    public PorcentajeDepreciacionAnualFactura(Factura factura, Double porcentaje, Date tiempoCreacion, Set<DeclaracionFactura> declaracionFacturas) {
       this.factura = factura;
       this.porcentaje = porcentaje;
       this.tiempoCreacion = tiempoCreacion;
       this.declaracionFacturas = declaracionFacturas;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="id", unique=true, nullable=false)
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="id_factura")
    public Factura getFactura() {
        return this.factura;
    }
    
    public void setFactura(Factura factura) {
        this.factura = factura;
    }

    
    @Column(name="porcentaje", nullable=false, precision=17, scale=17)
    public Double getPorcentaje() {
        return this.porcentaje;
    }
    
    public void setPorcentaje(Double porcentaje) {
        this.porcentaje = porcentaje;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="tiempo_creacion", nullable=false, length=29)
    public Date getTiempoCreacion() {
        return this.tiempoCreacion;
    }
    
    public void setTiempoCreacion(Date tiempoCreacion) {
        this.tiempoCreacion = tiempoCreacion;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="porcentajeDepreciacionAnualFactura")
    public Set<DeclaracionFactura> getDeclaracionFacturas() {
        return this.declaracionFacturas;
    }
    
    public void setDeclaracionFacturas(Set<DeclaracionFactura> declaracionFacturas) {
        this.declaracionFacturas = declaracionFacturas;
    }




}


